joint:
  names: [mx64]
motion:
  names: [right, zero, left]
  right:
    step: [-3.13] #[-3.14, -3.14]  # radian
    time_from_start: 3.0  # sec
  zero:
    step: [0.0] #[0.0, 0.0]
    time_from_start: 4.0
  left:
    step: [3.13] #[3.14, 3.14]
    time_from_start: 6.0

